parameters:
  - name: Daily
    type: boolean
    default: true
  - name: Artifact
    type: object
    default: {}
  - name: ArtifactName
    type: string
    default: ""
  - name: TimeoutInMinutes
    type: number
    default: 60

jobs:
  - job: SmokeTest
    steps:
      - task: PowerShell@2
        condition: and(succeeded(), ${{ parameters.Daily }})
        displayName: Building Package Info
        inputs:
          targetType: filePath
          filePath: ./eng/scripts/smoketest/Save-Package-Properties.ps1
          arguments: -outDirectory PackageInfo
          workingDirectory: common/SmokeTests/SmokeTest
          pwsh: true

      - template: /eng/pipelines/templates/steps/BuildSmokeTestProject.yml
        condition: and(succeeded(), ${{ parameters.Daily }})
        parameters:
          PackageInfoDir: common/SmokeTests/SmokeTest/PackageInfo
      
      - template: /eng/pipelines/templates/steps/BuildSmokeTestProject.yml
        condition: and(succeeded(), eq('${{ parameters.Daily }}', 'false'))
        parameters:
          PackageInfoDir: $(Build.ArtifactStagingDirectory)/PackageInfo

      - template: /eng/common/TestResources/remove-test-resources.yml
        parameters:
          ServiceDirectory: '$(Build.SourcesDirectory)/common/SmokeTests/'
          SubscriptionConfiguration: $(SubscriptionConfiguration)
